/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBoard: typeof import('./components/ActionBoard.vue')['default']
    ActionList: typeof import('./components/ActionList.vue')['default']
    ActionNewEdit: typeof import('./components/ActionNewEdit.vue')['default']
    ActionPlayerNewEdit: typeof import('./components/ActionPlayerNewEdit.vue')['default']
    ActionsList: typeof import('./components/ActionsList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Ball: typeof import('./components/Ball.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoardProgressBar: typeof import('./components/BoardProgressBar.vue')['default']
    PlayerCircle: typeof import('./components/PlayerCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
